package com.carty.riderapp.preference
//package com.servicely.customer.repository.preference

// Save all the label code here.
object PrefKeys {
    const val MSG_GM_SUCCESS: String = "MSG_GM_SUCCESS"
    const val MSG_GM_ERROR: String = "MSG_GM_ERROR"

    /////////////////////////////////////
    const val LBL_LANG_SCREEN_TITLE: String = "LBL_LANG_SCREEN_TITLE"
    const val LBL_LANG_SCREEN_DESCRIPTION: String = "LBL_LANG_SCREEN_DESCRIPTION"
    const val BTN_LANG_SCREEN_SPENISH: String = "BTN_LANG_SCREEN_SPENISH"
    const val INFO_MSG_LANG_PLEASE_CHECK_INTERNET_CONNECTION: String =
        "INFO_MSG_LANG_PLEASE_CHECK_INTERNET_CONNECTION"
    const val BTN_LANG_SCREEN_ENGLISH: String = "BTN_LANG_SCREEN_ENGLISH"
    const val INFO_MSG_LANG_SERVER_ISSUE_TRY_AGAIN: String = "INFO_MSG_LANG_SERVER_ISSUE_TRY_AGAIN"
    const val LBL_PACKAGE: String = "LBL_PACKAGE"
    const val INFO_MSG_ACCOUNT_DELETED_SUCCESSFULLY: String = "INFO_MSG_ACCOUNT_DELETED_SUCCESSFULLY"
    const val BTN_YES_SETTING: String = "BTN_YES_SETTING"
    const val BTN_CANCEL_SETTING: String = "BTN_CANCEL_SETTING"
    const val BTN_DIALOG_OK: String = "BTN_DIALOG_OK"

    const val LBL_CAMERA: String = "LBL_CAMERA"
    const val LBL_GALLARY: String = "LBL_GALLARY"
    const val LBL_CANCEL: String = "LBL_CANCEL"

    const val BTN_INTRO_SKIP: String = "BTN_INTRO_SKIP"
    const val BTN_INTRO_NEXT: String = "BTN_INTRO_NEXT"
    const val BTN_INTRO_GET_STARTED: String = "BTN_INTRO_GET_STARTED"
    const val LBL_INTRO_TITLE1: String = "LBL_INTRO_TITLE1"
    const val LBL_INTRO_DESC1: String = "LBL_INTRO_DESC1"
    const val LBL_INTRO_TITLE2: String = "LBL_INTRO_TITLE2"
    const val LBL_INTRO_DESC2: String = "LBL_INTRO_DESC2"
    const val LBL_INTRO_TITLE3: String = "LBL_INTRO_TITLE3"
    const val LBL_INTRO_DESC3: String = "LBL_INTRO_DESC3"

    const val HEADER_LOGIN_TITLE: String = "HEADER_LOGIN_TITLE"
    const val HEADER_LOGIN_SUBTITLE: String = "HEADER_LOGIN_SUBTITLE"
    const val PH_LOGIN_EMAILID: String = "PH_LOGIN_EMAILID"
    const val PH_LOGIN_PASSWORD: String = "PH_LOGIN_PASSWORD"
    const val LBL_LOGIN_REMEMBERME: String = "LBL_LOGIN_REMEMBERME"
    const val BTN_LOGIN_FORGOT_PSW: String = "BTN_LOGIN_FORGOT_PSW"
    const val BTN_LOGIN_LOGIN: String = "BTN_LOGIN_LOGIN"
    const val LBL_LOGIN_LOG_IN_WITH: String = "LBL_LOGIN_LOG_IN_WITH"
    const val BTN_LOGIN_GOOGLE: String = "BTN_LOGIN_GOOGLE"
    const val BTN_LOGIN_FACEBOOK: String = "BTN_LOGIN_FACEBOOK"
    const val BTN_LOGIN_SIGNUP: String = "BTN_LOGIN_SIGNUP"
    const val LBL_LOGIN_DONT_HAVE_ACCOUNT: String = "LBL_LOGIN_DONT_HAVE_ACCOUNT"
    const val INFO_MSG_LOGIN_PLEASE_ENTER_EMAILID: String = "INFO_MSG_LOGIN_PLEASE_ENTER_EMAILID"
    const val ERR_MSG_LOGIN_PLEASE_ENTER_VALID__EMAILID: String =
        "ERR_MSG_LOGIN_PLEASE_ENTER_VALID__EMAILID"
    const val INFO_MSG_LOGIN_PLEASE_ENTER_PASSWORD: String = "INFO_MSG_LOGIN_PLEASE_ENTER_PASSWORD"
    const val ERR_MSG_LOGIN_PLEASE_ENTER_VALID_PASSWORD: String =
        "ERR_MSG_LOGIN_PLEASE_ENTER_VALID_PASSWORD"
    const val ERR_MSG_LOGIN_PASSWORD_MUST_CONTAIN_SIX_CHAR: String =
        "ERR_MSG_LOGIN_PASSWORD_MUST_CONTAIN_SIX_CHAR"

    const val HEADER_SIGNUP_TITLE: String = "HEADER_SIGNUP_TITLE"
    const val HEADER_SIGNUP_SUBTITLE: String = "HEADER_SIGNUP_SUBTITLE"
    const val PH_SIGNUP_NAME: String = "PH_SIGNUP_NAME"
    const val PH_SIGNUP_MOBILE_NUMBER: String = "PH_SIGNUP_MOBILE_NUMBER"
    const val PH_SIGNUP_EMAILID: String = "PH_SIGNUP_EMAILID"
    const val PH_SIGNUP_SELECT_COUNTRY: String = "PH_SIGNUP_SELECT_COUNTRY"
    const val PH_SIGNUP_PASSWORD: String = "PH_SIGNUP_PASSWORD"
    const val LBL_SIGNUP_PRIVACY_POLICY: String = "LBL_SIGNUP_PRIVACY_POLICY"
    const val BTN_SIGNUP_SIGNUP: String = "BTN_SIGNUP_SIGNUP"
    const val LBL_SIGNUP_SIGN_UP_WITH: String = "LBL_SIGNUP_SIGN_UP_WITH"
    const val BTN_SIGNUP_GOOGLE: String = "BTN_SIGNUP_GOOGLE"
    const val BTN_SIGNUP_FACEBOOK: String = "BTN_SIGNUP_FACEBOOK"
    const val LBL_SIGNUP_PRIVACY: String = "LBL_SIGNUP_PRIVACY"
    const val LBL_SIGNUP_BY_TAPPING: String = "LBL_SIGNUP_BY_TAPPING"
    const val LBL_SIGNUP_AND: String = "LBL_SIGNUP_AND"
    const val LBL_SIGNUP_OF_THIS_APP: String = "LBL_SIGNUP_OF_THIS_APP"
    const val INFO_MSG_SIGNUP_PLEASE_ENTER_MOBILE_NUMBER: String =
        "INFO_MSG_SIGNUP_PLEASE_ENTER_MOBILE_NUMBER"
    const val ERR_MSG_SIGNUP_PLEASE_ENTER_VALID_MOBILE_NUMBER: String =
        "ERR_MSG_SIGNUP_PLEASE_ENTER_VALID_MOBILE_NUMBER"
    const val INFO_MSG_SIGNUP_PLEASE_ENTER_EMAILID: String = "INFO_MSG_SIGNUP_PLEASE_ENTER_EMAILID"


    const val ERR_MSG_SIGNUP_PLEASE_ENTER_VALID__EMAILID: String =
        "ERR_MSG_SIGNUP_PLEASE_ENTER_VALID__EMAILID"
    const val INFO_MSG_SIGNUP_PLEASE_ENTER_PASSWORD: String =
        "INFO_MSG_SIGNUP_PLEASE_ENTER_PASSWORD"
    const val ERR_MSG_SIGNUP_PLEASE_ENTER_VALID_PASSWORD: String =
        "ERR_MSG_SIGNUP_PLEASE_ENTER_VALID_PASSWORD"
    const val INFO_MSG_SIGNUP_PLEASE_ENTER_NAME: String = "INFO_MSG_SIGNUP_PLEASE_ENTER_NAME"
    const val ERR_MSG_SIGNUP_PLEASE_ENTER_VALID_NAME: String =
        "ERR_MSG_SIGNUP_PLEASE_ENTER_VALID_NAME"
    const val ERR_MSG_SIGNUP_PLEASE_SELECT_COUNTRY: String = "ERR_MSG_SIGNUP_PLEASE_SELECT_COUNTRY"

    const val HEADER_FORGOT_TITLE: String = "HEADER_FORGOT_TITLE"
    const val HEADER_FORGOT_SUBTITLE: String = "HEADER_FORGOT_SUBTITLE"
    const val PH_FORGOT_EMAILID: String = "PH_FORGOT_EMAILID"
    const val BTN_FORGOT_SEND: String = "BTN_FORGOT_SEND"
    const val INFO_MSG_FORGOT_PLEASE_ENTER_EMAILID: String = "INFO_MSG_FORGOT_PLEASE_ENTER_EMAILID"
    const val ERR_MSG_FORGOT_PLEASE_ENTER_VALID_EMAILID: String =
        "ERR_MSG_FORGOT_PLEASE_ENTER_VALID_EMAILID"

    const val HEADER_OTP_TITLE: String = "HEADER_OTP_TITLE"
    const val HEADER_OTP_SUBTITLE: String = "HEADER_OTP_SUBTITLE"
    const val LBL_OTP_DIDNT_YOU_RECIVED_CLICK: String = "LBL_OTP_DIDNT_YOU_RECIVED_CLICK"
    const val BTN_OTP_RESEND: String = "BTN_OTP_RESEND"
    const val LBL_OTP_RESEND_IN: String = "LBL_OTP_RESEND_IN"
    const val BTN_OTP_SEND: String = "BTN_OTP_SEND"
    const val BTN_OTP_SENDED_SUCCESSFULLY: String = "BTN_OTP_SENDED_SUCCESSFULLY"
    const val INFO_MSG_OTP_PLEASE_ENTER_OTP_CODE: String = "INFO_MSG_OTP_PLEASE_ENTER_OTP_CODE"
    const val ERR_MSG_OTP_PLEASE_ENTER_VALID_OTP_CODE: String =
        "ERR_MSG_OTP_PLEASE_ENTER_VALID_OTP_CODE"

    const val HEADER_RESET_TITLE: String = "HEADER_RESET_TITLE"
    const val HEADER_RESET_SUBTITLE: String = "HEADER_RESET_SUBTITLE"
    const val PH_RESET_PASSWORD: String = "PH_RESET_PASSWORD"
    const val PH_RESET_CONF_PASSWORD: String = "PH_RESET_CONF_PASSWORD"
    const val BTN_RESET_SUBMIT: String = "BTN_RESET_SUBMIT"
    const val INFO_MSG_RESET_PLEASE_ENTER_CONFIRM_PSW: String =
        "INFO_MSG_RESET_PLEASE_ENTER_CONFIRM_PSW"
    const val INFO_MSG_RESET_PLEASE_ENTER_PASSWORD: String = "INFO_MSG_RESET_PLEASE_ENTER_PASSWORD"
    const val ERR_MSG_RESET_PLEASE_ENTER_VALID_PASSWORD: String =
        "ERR_MSG_RESET_PLEASE_ENTER_VALID_PASSWORD"
    const val ERR_MSG_RESET_CONFIRM_PASSWORD_DID_NOT_MATCH: String =
        "ERR_MSG_RESET_CONFIRM_PASSWORD_DID_NOT_MATCH"
    const val ERR_MSG_RESET_PASSWORD_MUST_CONTAIN_SIX_CHAR: String =
        "ERR_MSG_RESET_PASSWORD_MUST_CONTAIN_SIX_CHAR"
    const val INFO_MSG_PASSWORD_HAS_BEEN_CHANGED_SUCCESSFULLY: String =
        "INFO_MSG_PASSWORD_HAS_BEEN_CHANGED_SUCCESSFULLY"

    const val LBL_SIDEMENU_HOME: String = "LBL_SIDEMENU_HOME"
    const val LBL_SIDEMENU_MYORDER: String = "LBL_SIDEMENU_MYORDER"
    const val LBL_SIDEMENU_HELP: String = "LBL_SIDEMENU_HELP"
    const val LBL_SIDEMENU_SETTINGS: String = "LBL_SIDEMENU_SETTINGS"
    const val LBL_SIDEMENU_INVITE_FRIEND: String = "LBL_SIDEMENU_INVITE_FRIEND"
    const val LBL_SIDEMENU_LOGOUT: String = "LBL_SIDEMENU_LOGOUT"
    const val INFO_MSG_ARE_YOU_SURE_YOU_WANT_TO_LOGOUT: String = "INFO_MSG_ARE_YOU_SURE_YOU_WANT_TO_LOGOUT"
    const val LBL_YES: String = "LBL_YES"
    const val LBL_SIDEMENU_CANCEL: String = "LBL_SIDEMENU_CANCEL"
    const val INFO_MSG_YOU_HAVE_LOGGIN_INTO_NEW_DEVIDE: String = "INFO_MSG_YOU_HAVE_LOGGIN_INTO_NEW_DEVIDE"
    const val LBL_NO_ANY_FAVOURITE_ADDRESS_AVAILABLE: String =
        "LBL_NO_ANY_FAVOURITE_ADDRESS_AVAILABLE"

    const val HEADER_HOME_TITLE: String = "HEADER_HOME_TITLE"
    const val LBL_HOME_STEP1: String = "LBL_HOME_STEP1"
    const val LBL_HOME_STEP2: String = "LBL_HOME_STEP2"
    const val LBL_HOME_STEP3: String = "LBL_HOME_STEP3"
    const val LBL_HOME_STEP4: String = "LBL_HOME_STEP4"
    const val LBL_HOME_SOURCE_ADDRESS: String = "LBL_HOME_SOURCE_ADDRESS"
    const val LBL_HOME_DESTINATION_ADDRESS: String = "LBL_HOME_DESTINATION_ADDRESS"
    const val LBL_HOME_ADDITIONAL_DROP_OFF_POINT: String = "LBL_HOME_ADDITIONAL_DROP_OFF_POINT"
    const val BTN_OTP_SERVICE_DETAILS: String = "BTN_OTP_SERVICE_DETAILS"

    const val HEADER_PICKUP_LOCATION_TITLE: String = "HEADER_PICKUP_LOCATION_TITLE"
    const val HEADER_DROPOFF_LOCATION_TITLE: String = "HEADER_DROPOFF_LOCATION_TITLE"
    const val LBL_PICKUP_LOCATION_BY_MAP: String = "LBL_PICKUP_LOCATION_BY_MAP"
    const val LBL_PICKUP_LOCATION_MY_FAVORITE: String = "LBL_PICKUP_LOCATION_MY_FAVORITE"
    const val BTN_PICKUP_LOCATION_BY_MAP_ADD: String = "BTN_PICKUP_LOCATION_BY_MAP_ADD"
    const val BTN_PICKUP_LOCATION_BY_MAP_DONE: String = "BTN_PICKUP_LOCATION_BY_MAP_DONE"
    const val LBL_ENTER_ADDRESS: String = "LBL_ENTER_ADDRESS"
    const val INFO_MSG_PLEASE_SELECT_ADDRESS: String = "INFO_MSG_PLEASE_SELECT_ADDRESS"

    const val HEADER_ADD_ADDRESS_TITLE: String = "HEADER_ADD_ADDRESS_TITLE"
    const val LBL_UPDATE_ADDRESS: String = "LBL_UPDATE_ADDRESS"
    const val BTN_ADD_ADDRESS_PICK_ON_MAP: String = "BTN_ADD_ADDRESS_PICK_ON_MAP"
    const val PH_ADD_ADDRESS_PLACE_NAME: String = "PH_ADD_ADDRESS_PLACE_NAME"
    const val PH_ADD_ADDRESS_PLACE_ADDRESS: String = "PH_ADD_ADDRESS_PLACE_ADDRESS"
    const val BTN_ADD_ADDRESS_SAVE_PLACE: String = "BTN_ADD_ADDRESS_SAVE_PLACE"
    const val INFO_MSG_ADD_ADDRESS_PLEASE_ENTER_PLACE_NAME: String =
        "INFO_MSG_ADD_ADDRESS_PLEASE_ENTER_PLACE_NAME"
    const val ERR_MSG_ADD_ADDRESS_PLEASE_ENTER_VALID__PLACE_NAME: String =
        "ERR_MSG_ADD_ADDRESS_PLEASE_ENTER_VALID__PLACE_NAME"
    const val INFO_MSG_ADD_ADDRESS_PLEASE_ENTER_PLACE_ADDRESS: String =
        "INFO_MSG_ADD_ADDRESS_PLEASE_ENTER_PLACE_ADDRESS"
    const val ERR_MSG_ADD_ADDRESS_PLEASE_ENTER_VALID_PLACE_ADDRESS: String =
        "ERR_MSG_ADD_ADDRESS_PLEASE_ENTER_VALID_PLACE_ADDRESS"

    const val HEADER_ADD_ADDRESS_PICK_LOCATION_TITLE: String =
        "HEADER_ADD_ADDRESS_PICK_LOCATION_TITLE"
    const val LBL_ADD_ADDRESS_PICKUP_LOCATION_ADDRESS: String =
        "LBL_ADD_ADDRESS_PICKUP_LOCATION_ADDRESS"
    const val BTN_ADD_ADDRESS_PICKUP_LOCATION_BY_MAP_ADD: String =
        "BTN_ADD_ADDRESS_PICKUP_LOCATION_BY_MAP_ADD"
    const val INFO_MSG_ADDRESS_DELETED_SUCCESSFULLY: String =
        "INFO_MSG_ADDRESS_DELETED_SUCCESSFULLY"
    const val BTN_ADD_ADDRESS_PICKUP_LOCATION_SAVE_PLACE: String =
        "BTN_ADD_ADDRESS_PICKUP_LOCATION_SAVE_PLACE"
    const val INFO_MSG_PLEASE_ENTER_VALID_ADDRESS: String =
        "INFO_MSG_PLEASE_ENTER_VALID_ADDRESS"

    const val LBL_BANK_DETAILS: String = "LBL_BANK_DETAILS"
    const val INFO_MSG_PLEASE_SELECT_BANK: String = "INFO_MSG_PLEASE_SELECT_BANK"
    const val INFO_MSG_ARE_YOU_SURE_YOU_WANT_TO_DELETE_THIS_RECORD: String = "INFO_MSG_ARE_YOU_SURE_YOU_WANT_TO_DELETE_THIS_RECORD"
    const val LBL_DELETE: String = "LBL_DELETE"
    const val LBL_CANCEL_BANKDETAIL: String = "LBL_CANCEL_BANKDETAIL"
    const val LBL_DONE: String = "LBL_DONE"

    const val BTN_UPDATE: String = "BTN_UPDATE"
    const val BTN_SUBMIT: String = "BTN_SUBMIT"
    const val LBL_BANK_ACCOUNTS: String = "LBL_BANK_ACCOUNTS"
    const val LBL_ENTER_NAME: String = "LBL_ENTER_NAME"
    const val LBL_ACCOUNT_NUMBER: String = "LBL_ACCOUNT_NUMBER"
    const val LBL_IFSC_CODE: String = "LBL_IFSC_CODE"

    const val INFO_MSG_PLEASE_ENTER_VALID_ACCOUNT_NUMBER: String = "INFO_MSG_PLEASE_ENTER_VALID_ACCOUNT_NUMBER"

    const val MSG_PLEASE_SELECT_PICKUP_ADDRESS: String = "MSG_PLEASE_SELECT_PICKUP_ADDRESS"
    const val MSG_PLEASE_SELECT_DROPOFF_ADDRESS: String = "MSG_PLEASE_SELECT_DROPOFF_ADDRESS"
    const val MSG_PICKUP_AND_DROPOFF_ADDRESS_MUST_NOT_BE_SAME: String =
        "MSG_PICKUP_AND_DROPOFF_ADDRESS_MUST_NOT_BE_SAME"
    const val INFO_MSG_PLEASE_SELECT_ANY_CATEGORY: String = "INFO_MSG_PLEASE_SELECT_ANY_CATEGORY"
    const val INFO_MSG_PLEASE_ENTER_IFSC_CODE: String = "INFO_MSG_PLEASE_ENTER_IFSC_CODE"
    const val INFO_MSG_BANK_DETAILS_ADDED_SUCCESSFULLY: String = "INFO_MSG_BANK_DETAILS_ADDED_SUCCESSFULLY"
    const val INFO_MSG_PLEASE_ENTER_BANK_NAME: String = "INFO_MSG_PLEASE_ENTER_BANK_NAME"
    const val INFO_MSG_PLEASE_ENTER_ACCOUNT_NUMBER: String = "INFO_MSG_PLEASE_ENTER_ACCOUNT_NUMBER"


    const val HEADER_SERVICE_TITLE: String = "HEADER_SERVICE_TITLE"
    const val LBL_SERVICE_STEP1: String = "LBL_SERVICE_STEP1"
    const val LBL_SERVICE_STEP2: String = "LBL_SERVICE_STEP2"
    const val LBL_SERVICE_STEP3: String = "LBL_SERVICE_STEP3"
    const val LBL_SERVICE_STEP4: String = "LBL_SERVICE_STEP4"
    const val LBL_SERVICE_SELECT_SERVICES: String = "LBL_SERVICE_SELECT_SERVICES"
    const val LBL_SERVICE_SELECT_PICKUP_TIME: String = "LBL_SERVICE_SELECT_PICKUP_TIME"
    const val ERR_MSG_SELECT_DROP_OFF_TIME: String = "ERR_MSG_SELECT_DROP_OFF_TIME"
    const val LBL_SERVICE_SELECT_DATE_TIME: String = "LBL_SERVICE_SELECT_DATE_TIME"
    const val LBL_SERVICE_PACKAGE: String = "LBL_SERVICE_PACKAGE"
    const val LBL_UPLOAD_FILE: String = "LBL_UPLOAD_FILE"
    const val LBL_ADD: String = "LBL_ADD"
    const val LBL_PACKAGE_QUANTITY: String = "LBL_PACKAGE_QUANTITY"
    const val LBL_SERVICE_SELECT_PACK_DIMEN: String = "LBL_SERVICE_SELECT_PACK_DIMEN"
    const val LBL_SERVICE_PACKAGES_WEIGHT: String = "LBL_SERVICE_PACKAGES_WEIGHT"
    const val LBL_SERVICE_SELECT_VEHICLES: String = "LBL_SERVICE_SELECT_VEHICLES"
    const val PH_SERVICE_ENTER_PACKAGE_WEIGHT: String = "PH_SERVICE_ENTER_PACKAGE_WEIGHT"
    const val LBL_SERVICE_CHOOSE_VEHICLE: String = "LBL_SERVICE_CHOOSE_VEHICLE"
    const val LBL_SERVICE_PAYMENT_METHOD: String = "LBL_SERVICE_PAYMENT_METHOD"
    const val LBL_SERVICE_PHOTO_MEDIA: String = "LBL_SERVICE_PHOTO_MEDIA"
    const val BTN_SERVICE_CONTACT_DETAILS: String = "BTN_SERVICE_CONTACT_DETAILS"
    const val INFO_MSG_PLEASE_SELECT_SERVICE_CATEGORY: String =
        "INFO_MSG_PLEASE_SELECT_SERVICE_CATEGORY"
    const val INFO_MSG_PLEASE_SELECT_SERVICE_SUBCATEGORY: String =
        "INFO_MSG_PLEASE_SELECT_SERVICE_SUBCATEGORY"
    const val INFO_MSG_PLEASE_SELECT_PICK_UP_DATE_TIME: String =
        "INFO_MSG_PLEASE_SELECT_PICK_UP_DATE_TIME"
    const val INFO_MSG_PLEASE_SELECT_DROP_OFFDATE_TIME: String =
        "INFO_MSG_PLEASE_SELECT_DROP_OFFDATE_TIME"
    const val INFO_MSG_PICK_UP_AND_DROP_OFF_DATE_TIME_MUST_NOT_BE_SAME: String =
        "INFO_MSG_PICK_UP_AND_DROP_OFF_DATE_TIME_MUST_NOT_BE_SAME"
    const val INFO_MSG_PLEASE_ENTER: String = "INFO_MSG_PLEASE_ENTER"
    const val INFO_MSG_PLEASE_SELECT_VEHICLE: String = "INFO_MSG_PLEASE_SELECT_VEHICLE"
    const val INFO_MSG_PLEASE_UPLOAD_ORDER_PHOTO: String = "INFO_MSG_PLEASE_UPLOAD_ORDER_PHOTO"
    const val INFO_MSG_DATE_TIME_VALIDATION: String = "INFO_MSG_DATE_TIME_VALIDATION"
    const val INFO_MSG_YOU_CANT_SELECT_TIME_BELOW_CURRENT_TIME: String = "INFO_MSG_YOU_CANT_SELECT_TIME_BELOW_CURRENT_TIME"
    const val LBL_MINUTES: String = "LBL_MINUTES"
    const val LBL_HOUR: String = "LBL_HOUR"

    const val INFO_MSG_SERVICE_PLEASE_ENTER_PACKAGE_WEIGHT: String =
        "INFO_MSG_SERVICE_PLEASE_ENTER_PACKAGE_WEIGHT"
    const val ERR_MSG_SERVICE_PLEASE_ENTER_VALID_PACKAGE_WEIGHT: String =
        "ERR_MSG_SERVICE_PLEASE_ENTER_VALID_PACKAGE_WEIGHT"
    const val ERR_MSG_SERVICE_PLEASE_SELECT_PICKUP_DATE_AND_TIME: String =
        "ERR_MSG_SERVICE_PLEASE_SELECT_PICKUP_DATE_AND_TIME"
    const val ERR_MSG_SERVICE_PLEASE_SELECT_PACKAGE_DIMNENSION: String =
        "ERR_MSG_SERVICE_PLEASE_SELECT_PACKAGE_DIMNENSION"
    const val ERR_MSG_SERVICE_PLEASE_CHOOSE_VEHICLE: String =
        "ERR_MSG_SERVICE_PLEASE_CHOOSE_VEHICLE"
    const val ERR_MSG_SERVICE_PLEASE_UPLOAD_PHOTO_MEDIA_FILE: String =
        "ERR_MSG_SERVICE_PLEASE_UPLOAD_PHOTO_MEDIA_FILE"
    const val ERR_MSG_SERVICE_PLEASE_SELECT_SERVICES: String =
        "ERR_MSG_SERVICE_PLEASE_SELECT_SERVICES"
    const val ERR_MSG_SERVICE_PLEASE_SELECT_PAYMENT_METHOD: String =
        "ERR_MSG_SERVICE_PLEASE_SELECT_PAYMENT_METHOD"

    const val HEADER_SUBSERVICES_TITLE: String = "HEADER_SUBSERVICES_TITLE"
    const val LBL_SUBSERVICES_CONSTRUCTION_METERIALS: String =
        "LBL_SUBSERVICES_CONSTRUCTION_METERIALS"
    const val BTN_SUBSERVICES_DONE: String = "BTN_SUBSERVICES_DONE"

    const val HEADER_CONTACT_DETAILS_TITLE: String = "HEADER_CONTACT_DETAILS_TITLE"
    const val LBL_CONTACT_DETAILS_STEP1: String = "LBL_CONTACT_DETAILS_STEP1"
    const val LBL_CONTACT_DETAILS_STEP2: String = "LBL_CONTACT_DETAILS_STEP2"
    const val LBL_CONTACT_DETAILS_STEP3: String = "LBL_CONTACT_DETAILS_STEP3"
    const val LBL_CONTACT_DETAILS_STEP4: String = "LBL_CONTACT_DETAILS_STEP4"
    const val LBL_CONTACT_DETAILS: String = "LBL_CONTACT_DETAILS"
    const val LBL_CONTACT_DETAILS_NAME: String = "LBL_CONTACT_DETAILS_NAME"
    const val PH_CONTACT_DETAILS_ENTER_YOUR_NAME: String = "PH_CONTACT_DETAILS_ENTER_YOUR_NAME"
    const val LBL_CONTACT_DETAILS_ENTER_PHONE_NUMBER: String =
        "LBL_CONTACT_DETAILS_ENTER_PHONE_NUMBER"
    const val PH_CONTACT_DETAILS_ENTER_YOUR_PHONE_NUMBER: String =
        "PH_CONTACT_DETAILS_ENTER_YOUR_PHONE_NUMBER"
    const val LBL_CONTACT_DETAILS_RECEIVER_CONTACT_DETAILS: String =
        "LBL_CONTACT_DETAILS_RECEIVER_CONTACT_DETAILS"
    const val LBL_CONTACT_DETAILS_RECEIVER_NAME: String = "LBL_CONTACT_DETAILS_RECEIVER_NAME"
    const val PH_CONTACT_DETAILS_ENTER_RECEIVER_NAME: String =
        "PH_CONTACT_DETAILS_ENTER_RECEIVER_NAME"
    const val LBL_CONTACT_DETAILS_ENTER_RECEIVER_PHONE_NUMBER: String =
        "LBL_CONTACT_DETAILS_ENTER_RECEIVER_PHONE_NUMBER"
    const val PH_CONTACT_DETAILS_ENTER_RECEIVER_PHONE_NUMBER: String =
        "PH_CONTACT_DETAILS_ENTER_RECEIVER_PHONE_NUMBER"
    const val BTN_CONTACT_DETAILS_REVIEW_ORDER: String = "BTN_CONTACT_DETAILS_REVIEW_ORDER"
    const val LBL_PICKUP_INSTRUCTION: String = "LBL_PICKUP_INSTRUCTION"
    const val LBL_ENTER_PICKUP_INSTRUCTION: String = "LBL_ENTER_PICKUP_INSTRUCTION"
    const val LBL_DROPOFF_INSTRUCTION: String = "LBL_DROPOFF_INSTRUCTION"
    const val LBL_ENTER_DROPOFF_INSTRUCTION: String = "LBL_ENTER_DROPOFF_INSTRUCTION"
    const val LBL_DO_YOU_HAVE_A_COUPON_CODE: String = "LBL_DO_YOU_HAVE_A_COUPON_CODE"
    const val LBL_APPLY: String = "LBL_APPLY"
    const val LBL_ENTER_COUPON_CODE: String = "LBL_ENTER_COUPON_CODE"
    const val INFO_MSG_PLEASE_ENTER_COUPON_CODE: String = "INFO_MSG_PLEASE_ENTER_COUPON_CODE"
    const val INFO_MSG_CONTACT_DETAILS_PLEASE_ENTER_YOUR_NAME: String =
        "INFO_MSG_CONTACT_DETAILS_PLEASE_ENTER_YOUR_NAME"
    const val ERR_MSG_CONTACT_DETAILS_PLEASE_ENTER_VALID_YOUR_NAME: String =
        "ERR_MSG_CONTACT_DETAILS_PLEASE_ENTER_VALID_YOUR_NAME"
    const val INFO_MSG_CONTACT_DETAILS_PLEASE_ENTER_YOUR_PHONE_NUMBER: String =
        "INFO_MSG_CONTACT_DETAILS_PLEASE_ENTER_YOUR_PHONE_NUMBER"
    const val ERR_MSG_CONTACT_DETAILS_PLEASE_ENTER_VALID_YOUR_PHONE_NUMBER: String =
        "ERR_MSG_CONTACT_DETAILS_PLEASE_ENTER_VALID_YOUR_PHONE_NUMBER"
    const val INFO_MSG_CONTACT_DETAILS_PLEASE_ENTER_RECEIVER_NAME: String =
        "INFO_MSG_CONTACT_DETAILS_PLEASE_ENTER_RECEIVER_NAME"
    const val ERR_MSG_CONTACT_DETAILS_PLEASE_ENTER_VALID_RECEIVER_NAME: String =
        "ERR_MSG_CONTACT_DETAILS_PLEASE_ENTER_VALID_RECEIVER_NAME"
    const val INFO_MSG_CONTACT_DETAILS_PLEASE_ENTER_RECEIVER_PHONE_NUMBER: String =
        "INFO_MSG_CONTACT_DETAILS_PLEASE_ENTER_RECEIVER_PHONE_NUMBER"
    const val ERR_MSG_CONTACT_DETAILS_PLEASE_ENTER_VALID_RECEIVER_PHONE_NUMBER: String =
        "ERR_MSG_CONTACT_DETAILS_PLEASE_ENTER_VALID_RECEIVER_PHONE_NUMBER"
    const val INFO_MSG_PLEASE_ENTER_PICKUP_INSTRUCTION: String =
        "INFO_MSG_PLEASE_ENTER_PICKUP_INSTRUCTION"
    const val INFO_MSG_PLEASE_ENTER_DROPOFF_INSTRUCTION: String =
        "INFO_MSG_PLEASE_ENTER_DROPOFF_INSTRUCTION"

    const val HEADER_REVIEW_ORDER_TITLE: String = "HEADER_REVIEW_ORDER_TITLE"
    const val LBL_REVIEW_ORDER_STEP1: String = "LBL_REVIEW_ORDER_STEP1"
    const val LBL_REVIEW_ORDER_STEP2: String = "LBL_REVIEW_ORDER_STEP2"
    const val LBL_REVIEW_ORDER_STEP3: String = "LBL_REVIEW_ORDER_STEP3"
    const val LBL_REVIEW_ORDER_STEP4: String = "LBL_REVIEW_ORDER_STEP4"
    const val LBL_REVIEW_ORDER_PICKUP_ADDRESS: String = "LBL_REVIEW_ORDER_PICKUP_ADDRESS"
    const val LBL_REVIEW_ORDER_DESTINATION_ADDRESS: String = "LBL_REVIEW_ORDER_DESTINATION_ADDRESS"
    const val LBL_REVIEW_ORDER_PICKUP_DATE_TIME: String = "LBL_REVIEW_ORDER_PICKUP_DATE_TIME"
    const val LBL_REVIEW_ORDER_PHOTO: String = "LBL_REVIEW_ORDER_PHOTO"
    const val LBL_REVIEW_ORDER_PACKAGE: String = "LBL_REVIEW_ORDER_PACKAGE"
    const val LBL_REVIEW_ORDER_WIDTH: String = "LBL_REVIEW_ORDER_WIDTH"
    const val LBL_REVIEW_ORDER_HEIGHT: String = "LBL_REVIEW_ORDER_HEIGHT"
    const val LBL_REVIEW_ORDER_WEIGHT: String = "LBL_REVIEW_ORDER_WEIGHT"
    const val LBL_REVIEW_ORDER_SENDER_INFO: String = "LBL_REVIEW_ORDER_SENDER_INFO"
    const val LBL_REVIEW_ORDER_RECEIVER_INFO: String = "LBL_REVIEW_ORDER_RECEIVER_INFO"
    const val LBL_REVIEW_ORDER_PAYMENT_METHOD: String = "LBL_REVIEW_ORDER_PAYMENT_METHOD"
    const val LBL_REVIEW_ORDER_CASH_ON_DELIVERY: String = "LBL_REVIEW_ORDER_CASH_ON_DELIVERY"
    const val BTN_REVIEW_ORDER_DONE: String = "BTN_REVIEW_ORDER_DONE"
    const val LBL_ESTIMATED_DISTANCE: String = "LBL_ESTIMATED_DISTANCE"
    const val LBL_ESTIMATED_TIME: String = "LBL_ESTIMATED_TIME"
    const val LBL_SERVICES: String = "LBL_SERVICES"
    const val LBL_VEHICLE: String = "LBL_VEHICLE"
    const val LBL_DROP_OFF_DATE_TIME: String = "LBL_DROP_OFF_DATE_TIME"
    const val LBL_PHOTOS: String = "LBL_PHOTOS"
    const val LBL_PACKAGE_QUANTITY_: String = "LBL_PACKAGE_QUANTITY"
    const val LBL_PRICE: String = "LBL_PRICE"
    const val LBL_TOTAL_PRICE: String = "LBL_TOTAL_PRICE"
    const val LBL_DISCOUNT: String = "LBL_DISCOUNT"
    const val LBL_AMOUNT_TO_PAY: String = "LBL_AMOUNT_TO_PAY"
    const val LBL_ADD_PAYMENT: String = "LBL_ADD_PAYMENT"
    const val LBL_NAME: String = "LBL_NAME"
    const val LBL_INSTRUCTION: String = "LBL_INSTRUCTION"
    const val LBL_PHONE_NUMBER: String = "LBL_PHONE_NUMBER"
    const val INFO_MSG_PLEASE_SELECT_PAYMENT_METHOD: String =
        "INFO_MSG_PLEASE_SELECT_PAYMENT_METHOD"
    const val INFO_MSG_PLEASE_SELECT_ANY_CREDIT_CARD: String =
        "INFO_MSG_PLEASE_SELECT_ANY_CREDIT_CARD"
    const val INFO_MSG_ORDER_PLACED_SUCCESSFULLY: String = "INFO_MSG_ORDER_PLACED_SUCCESSFULLY"

    const val HEADER_MY_ORDERS_TITLE: String = "HEADER_MY_ORDERS_TITLE"
    const val LBL_MY_ORDERS_COMING: String = "LBL_MY_ORDERS_COMING"
    const val LBL_MY_ORDERS_HISTORY: String = "LBL_MY_ORDERS_HISTORY"

    const val LBL_ORDER_DETAILS_DISTANCE: String = "LBL_ORDER_DETAILS_DISTANCE"
    const val LBL_ORDER_DETAILS_TIME: String = "LBL_ORDER_DETAILS_TIME"
    const val LBL_ORDER_DETAILS_TOTAL_FARE: String = "LBL_ORDER_DETAILS_TOTAL_FARE"
    const val LBL_ORDER_DETAILS_PAYMENT_METHOD: String = "LBL_ORDER_DETAILS_PAYMENT_METHOD"
    const val BTN_ORDER_DETAILS_CANCEL_ORDER: String = "BTN_ORDER_DETAILS_CANCEL_ORDER"

    const val HEADER_HELP_TITLE: String = "HEADER_HELP_TITLE"
    const val BTN_HELP_CONTACT_US: String = "BTN_HELP_CONTACT_US"
    const val BTN_HELP_FEEDBACK: String = "BTN_HELP_FEEDBACK"
    const val LBL_HELP_QUES: String = "LBL_HELP_QUES"
    const val LBL_HELP_PAYMENTS: String = "LBL_HELP_PAYMENTS"
    const val LBL_HELP_VEHICLES: String = "LBL_HELP_VEHICLES"
    const val LBL_HELP_COUPONS_CREDIT: String = "LBL_HELP_COUPONS_CREDIT"
    const val LBL_HELP_IS_THERE_DRIVER_APP_AVAIL_ON: String =
        "LBL_HELP_IS_THERE_DRIVER_APP_AVAIL_ON"
    const val LBL_HELP_COUPONS_CAN_DRIVER_CHOOSE_ANOTHER: String =
        "LBL_HELP_COUPONS_CAN_DRIVER_CHOOSE_ANOTHER"
    const val LBL_HELP_CAN_THE_DRIVER_BE_THE_DISPATHER: String =
        "LBL_HELP_CAN_THE_DRIVER_BE_THE_DISPATHER"
    const val LBL_HELP_HOW_DO_I_CAHNGE: String = "LBL_HELP_HOW_DO_I_CAHNGE"
    const val LBL_HELP_IF_THERE_ARE_PLACES_WITH_POOR: String =
        "LBL_HELP_IF_THERE_ARE_PLACES_WITH_POOR"
    const val LBL_HELP_I_HAVE_ANOTHER_TYPE_OF: String = "LBL_HELP_I_HAVE_ANOTHER_TYPE_OF"
    const val LBL_HELP_HOW_DO_I_SIGNUP: String = "LBL_HELP_HOW_DO_I_SIGNUP"

    const val HEADER_FEEDBACK_TITLE: String = "HEADER_FEEDBACK_TITLE"
    const val LBL_FEEDBACK_GOOD: String = "LBL_FEEDBACK_GOOD"
    const val BTN_FEEDBACK_DONE: String = "BTN_FEEDBACK_DONE"
    const val HEADER_FEEDBACK_SUBTITLE: String = "HEADER_FEEDBACK_SUBTITLE"
    const val INFO_MSG_PLEASE_ENTER_YOUR_FEEDBACK: String = "INFO_MSG_PLEASE_ENTER_YOUR_FEEDBACK"
    const val INFO_MSG_FEEDBACK_SUBMITTED_SUCCESSFULLY: String = "INFO_MSG_FEEDBACK_SUBMITTED_SUCCESSFULLY"

    const val HEADER_CONTACTUS_TITLE: String = "HEADER_CONTACTUS_TITLE"
    const val HEADER_CONTACTUS_SUBTITLE: String = "HEADER_CONTACTUS_SUBTITLE"
    const val LBL_CONTACTUS_EMAIL: String = "LBL_CONTACTUS_EMAIL"
    const val LBL_CONTACTUS_PHONE: String = "LBL_CONTACTUS_PHONE"
    const val PH_CONTACTUS_TYPE_YOUR_ISSUE_HERE: String = "PH_CONTACTUS_TYPE_YOUR_ISSUE_HERE"
    const val BTN_CONTACTUS_SUBMIT: String = "BTN_CONTACTUS_SUBMIT"
    const val ERR_MSG_CONTACTUS_PLEASE_ENTER_YOUR_ISSUE: String =
        "ERR_MSG_CONTACTUS_PLEASE_ENTER_YOUR_ISSUE"

    const val HEADER_SETTING_TITLE: String = "HEADER_SETTING_TITLE"
    const val LBL_SETTING_MANAGE_ADDRESS: String = "LBL_SETTING_MANAGE_ADDRESS"
    const val LBL_SETTING_NOTIFICATION: String = "LBL_SETTING_NOTIFICATION"
    const val LBL_SETTING_PRIVACY_POLICY: String = "LBL_SETTING_PRIVACY_POLICY"
    const val LBL_SETTING_TERMS_CONDITION: String = "LBL_SETTING_TERMS_CONDITION"
    const val LBL_SETTING_DELETE_ACCOUNT: String = "LBL_SETTING_DELETE_ACCOUNT"
    const val LBL_SETTING_LOGOUT: String = "LBL_SETTING_LOGOUT"
    const val LBL_SETTING_CHANGE_LANGUAGE: String = "LBL_SETTING_CHANGE_LANGUAGE"
    const val LBL_SETTING_ARE_YOU_SURE_YOU_WANT_TO_LOGOUT: String =
        "LBL_SETTING_ARE_YOU_SURE_YOU_WANT_TO_LOGOUT"
    const val LBL_SETTING_ARE_YOU_SURE_YOU_WANT_TO_DELETE_YOUR_ACCOUNT_PERMANENTLY: String =
        "LBL_SETTING_ARE_YOU_SURE_YOU_WANT_TO_DELETE_YOUR_ACCOUNT_PERMANENTLY"
    const val LBL_TYPE_YOUR_ISSUE_HERE: String = "LBL_TYPE_YOUR_ISSUE_HERE"
    const val LBL_NO_DATA_FOUND: String = "LBL_NO_DATA_FOUND"


    const val HEADER_PRIVACY_TITLE: String = "HEADER_PRIVACY_TITLE"

    const val HEADER_TERMS_TITLE: String = "HEADER_TERMS_TITLE"

    const val HEADER_MANAGE_ADDRESS_TITLE: String = "HEADER_MANAGE_ADDRESS_TITLE"

    const val HEADER_NOTIFICATION_TITLE: String = "HEADER_NOTIFICATION_TITLE"

    const val HEADER_INVITE_TITLE: String = "HEADER_INVITE_TITLE"
    const val LBL_SHARE_YOUR_INVITE_CODE: String = "LBL_SHARE_YOUR_INVITE_CODE"
    const val BTN_INVITE_SHARE: String = "BTN_INVITE_SHARE"
    const val LBL_INVITE_SHARE_YOUR_CODE_WITH_YOUR_FRIEND: String =
        "LBL_INVITE_SHARE_YOUR_CODE_WITH_YOUR_FRIEND"
    const val BTN_INVITE_SHARE_YOUR_CODE: String = "BTN_INVITE_SHARE_YOUR_CODE"
}